# risk_config.py

MAX_POSITIONS = 5
TRADE_AMOUNT_RATIO = 0.2
LEVERAGE = 5
FILTER_RATIO = 1.05
POSITION_RATIO = 0.25

# ORB 전략
ORB_TP_PERCENT = 2.0
ORB_SL_PERCENT = 1.0
ORB_TIMECUT_HOURS = 3

# NR7 전략
NR7_TP_PERCENT = 1.8
NR7_SL_PERCENT = 0.9
NR7_TIMECUT_HOURS = 3

# PULLBACK 전략
PULLBACK_TP_PERCENT = 1.2
PULLBACK_SL_PERCENT = 0.8
PULLBACK_REENTRY_TIMEOUT_MINUTES = 60  # ※ 추후 사용 가능

# EMA 전략
EMA_TP_PERCENT = 1.2
EMA_SL_PERCENT = 0.8
EMA_REENTRY_TIMEOUT_MINUTES = 60  # ※ 추후 사용 가능
