# risk_config.py

# 자산 대비 포지션 비율 및 레버리지 설정
POSITION_RATIO = 0.25
LEVERAGE = 5
MAX_POSITIONS = 5
MIN_NOTIONAL = 5.0  # 바이낸스 최소 거래 금액 기준

# 전략별 TP/SL 비율 (%)
ORB_TP_PERCENT = 2
ORB_SL_PERCENT = 1
ORB_TIMECUT_HOURS = 3

NR7_TP_PERCENT = 2
NR7_SL_PERCENT = 1
NR7_TIMECUT_HOURS = 3

EMA_TP_PERCENT = 1.8
EMA_SL_PERCENT = 1.2

PULLBACK_TP_PERCENT = 1.2
PULLBACK_SL_PERCENT = 0.8